version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: mentorship_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gargantuan_ball*
      POSTGRES_DB: mentorship_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: